# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_modelinstance', '0006_auto_20151216_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executedby',
            name='model_program_fk',
        ),
        migrations.AddField(
            model_name='executedby',
            name='model_url',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='executedby',
            name='model_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
