# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-06 19:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_composite_resource', '0001_initial'),
        ('hs_file_types', '0010_auto_20181209_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstanceFileMetadata',
            fields=[
                ('filesetmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hs_file_types.FileSetMetaData')),
            ],
            options={
                'abstract': False,
            },
            bases=('hs_file_types.filesetmetadata',),
        ),
        migrations.CreateModel(
            name='ModelInstanceLogicalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hs_file_types.ModelInstanceFileMetadata')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs_composite_resource.CompositeResource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
