# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-16 19:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_composite_resource', '0001_initial'),
        ('hs_core', '0042_auto_20190325_1856'),
        ('hs_file_types', '0010_auto_20181209_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstanceFileMetadata',
            fields=[
                ('coremetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hs_core.CoreMetaData')),
                ('extra_metadata', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=[], size=None)),
                ('is_dirty', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('hs_core.coremetadata', models.Model),
        ),
        migrations.CreateModel(
            name='ModelInstanceLogicalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hs_file_types.ModelInstanceFileMetadata')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs_composite_resource.CompositeResource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
